In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [5]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
a.shape

(2, 3)

In [7]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
input=np.array([1,2,3,4,5])

In [11]:
output=1/(1+np.exp(-input))

In [12]:
output

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715])

In [13]:
x=1/(1+np.exp(-1))

In [14]:
x

0.7310585786300049

In [15]:
np.vstack(np.array([1,2,3]),np.zeros(3))

TypeError: vstack() takes 1 positional argument but 2 were given

In [16]:
np.vstack((np.array([1,2,3]),np.zeros(3)))

array([[1., 2., 3.],
       [0., 0., 0.]])

In [17]:
np.pi

3.141592653589793

In [18]:
np.power(np.array([1,2,3]),2)

array([1, 4, 9])

In [19]:
1+2/3

1.6666666666666665

In [20]:
np.random.randn(2,3)

array([[-0.65078666, -0.5378966 ,  0.7432283 ],
       [-0.98930101,  0.06040453,  1.11934705]])

In [21]:
a=np.array([1,2,3])
b=np.array([[1,2],[3,4],[5,6]])
c=a@b

In [22]:
c

array([22, 28])

In [23]:
a@b+np.array([8,2])

array([30, 30])

In [25]:
a=np.array([1,2])
b=np.array([1,2,3])
c=np.outer(a,b)
print(c)

[[1 2 3]
 [2 4 6]]


# 计算范数

In [26]:
a=np.array([1,2,3])
b=np.linalg.norm(a,ord=1)
c=np.linalg.norm(a,ord=2)
print(b)
print(c)

6.0
3.7416573867739413


In [27]:
np.sqrt(14)

3.7416573867739413

# 计算outer

In [2]:
import numpy as np
batch_size=64
in_dim=256
out_dim=49
a=np.random.randn(batch_size,in_dim)
b=np.random.randn(out_dim)
c=np.outer(a,b)
print(c.shape)

(16384, 49)


In [3]:
c=a[:,:,np.newaxis]*b
print(c.shape)

(64, 256, 49)


In [5]:
c=a[:,np.newaxis,:]*b[:,None]
print(c.shape)

(64, 49, 256)


In [7]:
a=np.random.randn(2,3)
b=np.sum(a,axis=0)
print(b.shape)
print(a.shape)

(3,)
(2, 3)


In [8]:
a=np.random.randn(5)
b=np.random.randn(10)
c=np.outer(a,b)
print(c.shape)

(5, 10)
