In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [5]:
a=np.array([[1,2,3],[4,5,6]])

In [6]:
a.shape

(2, 3)

In [7]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
input=np.array([1,2,3,4,5])

In [11]:
output=1/(1+np.exp(-input))

In [12]:
output

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715])

In [13]:
x=1/(1+np.exp(-1))

In [14]:
x

0.7310585786300049

In [15]:
np.vstack(np.array([1,2,3]),np.zeros(3))

TypeError: vstack() takes 1 positional argument but 2 were given

In [16]:
np.vstack((np.array([1,2,3]),np.zeros(3)))

array([[1., 2., 3.],
       [0., 0., 0.]])

In [17]:
np.pi

3.141592653589793

In [18]:
np.power(np.array([1,2,3]),2)

array([1, 4, 9])

In [19]:
1+2/3

1.6666666666666665

In [20]:
np.random.randn(2,3)

array([[-0.65078666, -0.5378966 ,  0.7432283 ],
       [-0.98930101,  0.06040453,  1.11934705]])

In [21]:
a=np.array([1,2,3])
b=np.array([[1,2],[3,4],[5,6]])
c=a@b

In [22]:
c

array([22, 28])

In [23]:
a@b+np.array([8,2])

array([30, 30])

In [25]:
a=np.array([1,2])
b=np.array([1,2,3])
c=np.outer(a,b)
print(c)

[[1 2 3]
 [2 4 6]]


# 计算范数

In [26]:
a=np.array([1,2,3])
b=np.linalg.norm(a,ord=1)
c=np.linalg.norm(a,ord=2)
print(b)
print(c)

6.0
3.7416573867739413


In [27]:
np.sqrt(14)

3.7416573867739413

# 计算outer

In [2]:
import numpy as np
batch_size=64
in_dim=256
out_dim=49
a=np.random.randn(batch_size,in_dim)
b=np.random.randn(out_dim)
c=np.outer(a,b)
print(c.shape)

(16384, 49)


In [3]:
c=a[:,:,np.newaxis]*b
print(c.shape)

(64, 256, 49)


In [5]:
c=a[:,np.newaxis,:]*b[:,None]
print(c.shape)

(64, 49, 256)


In [7]:
a=np.random.randn(2,3)
b=np.sum(a,axis=0)
print(b.shape)
print(a.shape)

(3,)
(2, 3)


In [8]:
a=np.random.randn(5)
b=np.random.randn(10)
c=np.outer(a,b)
print(c.shape)

(5, 10)


# test broadcast for minus

In [10]:
a=np.arange(0,6).reshape(2,3)
b=np.arange(0,3)
c=a-b
print(a)
print(b)
print(c)

[[0 1 2]
 [3 4 5]]
[0 1 2]
[[0 0 0]
 [3 3 3]]


In [11]:
print(c.size)

6


In [12]:
np.log(np.e)

0.9999999999999999

# divide broadcast

In [14]:
a=np.random.randn(2,3)
b=np.random.randn(2)
c=a/b
print(c)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
a=np.random.randn(2,3)
b=np.random.randn(2)
c=a/b[:,np.newaxis]
print(c)

[[ 0.72110323 -0.23558325 -0.27537878]
 [ 0.99044317 -1.08063107  0.89978052]]


In [16]:
np.sum(a).shape

()

In [17]:
a=np.arange(0,6).reshape(2,3)
b=np.sum(a)
print(b)

15


In [3]:
import numpy as np
a=np.arange(0,6).reshape(2,3)
d=1-a
print(d)

[[ 1  0 -1]
 [-2 -3 -4]]


In [6]:
one_index=np.argmax(a,axis=1)
correct_score=a[np.arange(0,a.shape[0]),one_index]
print(one_index)
print(correct_score)
print(1-correct_score[:,np.newaxis]+a)

[2 2]
[2 5]
[[-1  0  1]
 [-1  0  1]]


In [8]:
b=1-correct_score[:,np.newaxis]+a
print(b>0)

[[False False  True]
 [False False  True]]


In [9]:
print(max(np.zeros(b.shape),b))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
print(np.maximum(0,b))

[[0 0 1]
 [0 0 1]]


In [11]:
print(b)

[[-1  0  1]
 [-1  0  1]]


In [13]:
np.sum(b>0,axis=1)

array([1, 1])

In [14]:
np.sum(b>0,axis=0)

array([0, 0, 2])

# np.where同样支持广播

In [18]:
a=np.random.randn(3,6)
b=np.random.randn(3)
c=np.where(a>0,b[:,np.newaxis],a)
print(b)
print(c)

[-2.92182549 -0.24470105 -1.87280078]
[[-0.3534276  -2.92182549 -2.92182549 -2.92182549 -1.39277695 -2.92182549]
 [-0.99252393 -0.24470105 -1.04533304 -0.24470105 -1.22244473 -1.02824174]
 [-0.58328243 -0.68633618 -1.87280078 -0.36726834 -0.52919298 -1.87280078]]


In [19]:
a=np.random.randn(3,6)
b=np.random.randn(3)
c=np.where(a>0,b[:,np.newaxis],0)
print(b)
print(c)

[-0.50241021 -2.18121565 -0.62308298]
[[ 0.          0.         -0.50241021 -0.50241021 -0.50241021 -0.50241021]
 [-2.18121565 -2.18121565 -2.18121565 -2.18121565  0.          0.        ]
 [-0.62308298  0.         -0.62308298 -0.62308298 -0.62308298 -0.62308298]]


In [20]:
for i in range(5,-1,-1):
    print(i)

5
4
3
2
1
0


In [21]:
from datetime import datetime
now=datetime.now()
print(now)

2023-10-05 19:45:39.645383


In [22]:
str(now).split(' ')[1][:-3]

'19:45:39.645'

# 测试返回多个值

In [3]:
def test_tuple():
    return 1,2
x=test_tuple()
print(x)
print(x[0])
print(x[1])


(1, 2)
1
2


In [8]:
import numpy as np
a=np.arange(0,100)
print(type(a))
b=[1,2,3,4,5]
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>
