In [1]:
import torch

In [6]:
a=torch.randn(1,2,3,4,5)
b=torch.randn(5,10)
c=torch.randn(10)

### torch.addmm()中的乘法必须是矩阵

In [7]:
d=torch.addmm(c,a,b)
d.shape

RuntimeError: mat1 must be a matrix, got 5-D tensor

In [8]:
a=(1,2,3,4,5)
b=(6,)
c=a+b
c

(1, 2, 3, 4, 5, 6)

In [3]:
a=torch.randn(1,2,3)

In [5]:
b=torch.stack((a,a,a),dim=1)
b.shape

torch.Size([1, 3, 2, 3])

In [6]:
b.size()

torch.Size([1, 3, 2, 3])

In [5]:
a=torch.randn(5)
b=a.repeat(5)
c=a.repeat(5,1)
print(b.shape)
print(c.shape)

torch.Size([25])
torch.Size([5, 5])


In [6]:
a=torch.randn(2,3)
b=a.repeat(4,1,1)
b.shape

torch.Size([4, 2, 3])

In [9]:
a=torch.randn(2,3)
print(a)
b=a[:,2]
print(b)
a[:,2]=1
print(a)

tensor([[-0.0216, -0.0878, -1.0608],
        [ 0.4372, -0.0298, -0.8636]])
tensor([-1.0608, -0.8636])
tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])


In [11]:
a.shape

torch.Size([2, 3])

In [12]:
torch.sum(a,0)

tensor([ 0.4156, -0.1176,  2.0000])

In [13]:
a.__len__

<bound method Tensor.__len__ of tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])>

In [14]:
print(a.__len__)

<bound method Tensor.__len__ of tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])>


In [18]:
a=torch.multinomial(torch.tensor([10.0,1,0]),1)
b=int(a)
print(a)
print(b)

tensor([0])
0


In [20]:
a=torch.multinomial(torch.ones(2,3),1)
a

tensor([[2],
        [1]])

In [22]:
a[:,0]

tensor([2, 1])

In [23]:
a[:,:1]

tensor([[2],
        [1]])

In [24]:
a=torch.arange(10)
a[:,None]

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [2]:
a=torch.randn(2,3)
b=torch.arange(6)
c=b.reshape(a.shape)
print(b)
print(c)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [4]:
a=torch.exp(torch.tensor([2]))
b=a.item()
a,b

(tensor([7.3891]), 7.389056205749512)