In [1]:
import torch

In [6]:
a=torch.randn(1,2,3,4,5)
b=torch.randn(5,10)
c=torch.randn(10)

### torch.addmm()中的乘法必须是矩阵

In [7]:
d=torch.addmm(c,a,b)
d.shape

RuntimeError: mat1 must be a matrix, got 5-D tensor

In [8]:
a=(1,2,3,4,5)
b=(6,)
c=a+b
c

(1, 2, 3, 4, 5, 6)

In [3]:
a=torch.randn(1,2,3)

In [5]:
b=torch.stack((a,a,a),dim=1)
b.shape

torch.Size([1, 3, 2, 3])

In [6]:
b.size()

torch.Size([1, 3, 2, 3])

In [5]:
a=torch.randn(5)
b=a.repeat(5)
c=a.repeat(5,1)
print(b.shape)
print(c.shape)

torch.Size([25])
torch.Size([5, 5])


In [6]:
a=torch.randn(2,3)
b=a.repeat(4,1,1)
b.shape

torch.Size([4, 2, 3])

In [9]:
a=torch.randn(2,3)
print(a)
b=a[:,2]
print(b)
a[:,2]=1
print(a)

tensor([[-0.0216, -0.0878, -1.0608],
        [ 0.4372, -0.0298, -0.8636]])
tensor([-1.0608, -0.8636])
tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])


In [11]:
a.shape

torch.Size([2, 3])

In [12]:
torch.sum(a,0)

tensor([ 0.4156, -0.1176,  2.0000])

In [13]:
a.__len__

<bound method Tensor.__len__ of tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])>

In [14]:
print(a.__len__)

<bound method Tensor.__len__ of tensor([[-0.0216, -0.0878,  1.0000],
        [ 0.4372, -0.0298,  1.0000]])>


In [18]:
a=torch.multinomial(torch.tensor([10.0,1,0]),1)
b=int(a)
print(a)
print(b)

tensor([0])
0


In [20]:
a=torch.multinomial(torch.ones(2,3),1)
a

tensor([[2],
        [1]])

In [22]:
a[:,0]

tensor([2, 1])

In [23]:
a[:,:1]

tensor([[2],
        [1]])

In [24]:
a=torch.arange(10)
a[:,None]

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [2]:
a=torch.randn(2,3)
b=torch.arange(6)
c=b.reshape(a.shape)
print(b)
print(c)

tensor([0, 1, 2, 3, 4, 5])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [4]:
a=torch.exp(torch.tensor([2]))
b=a.item()
a,b

(tensor([7.3891]), 7.389056205749512)

In [4]:
a=torch.randn(1,2,3)
a.shape

torch.Size([1, 2, 3])

In [2]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [3]:
a=torch.arange(9).reshape(3,3)
c=a[:,[1,2]]
c

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [4]:
d=a[:,(1,2)]
d

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [7]:
[1,20]+[2]

[1, 20, 2]

In [2]:
a=torch.arange(1,50)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [4]:
torch.cuda.is_available()

True

In [6]:
import numpy as np

In [7]:
a=np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [10]:
try:
    a[0][0]
except TypeError:
    print("hello")

IndexError: invalid index to scalar variable.

In [11]:
a=[0]*5
a

[0, 0, 0, 0, 0]

In [12]:
try:
    a[0][0]
except TypeError:
    print("hello")

hello


In [13]:
try:
    a[0][0]
except Exception as e:
    print(type(e))

<class 'TypeError'>


In [15]:
type(a)

list

In [16]:
a/=2
a

TypeError: unsupported operand type(s) for /=: 'list' and 'int'

In [17]:
b=np.ones(5)
type(b)

numpy.ndarray

In [3]:
a=torch.randn(2,3)
b=a.repeat(1,1,1,1)
b.shape

torch.Size([1, 1, 2, 3])

In [3]:
a=torch.load("/home/haoooooooooooookkkkk/sophomore_autumn/ANN/HW3/HW3/codes/pretrain/pretrained_ckpt.bin")

In [3]:
type(a)

collections.OrderedDict

In [4]:
a.keys()

odict_keys(['transformer.wte.weight', 'transformer.wpe.weight', 'transformer.h.0.ln_1.weight', 'transformer.h.0.ln_1.bias', 'transformer.h.0.attn.bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.0.attn.c_attn.weight', 'transformer.h.0.attn.c_attn.bias', 'transformer.h.0.attn.c_proj.weight', 'transformer.h.0.attn.c_proj.bias', 'transformer.h.0.ln_2.weight', 'transformer.h.0.ln_2.bias', 'transformer.h.0.mlp.c_fc.weight', 'transformer.h.0.mlp.c_fc.bias', 'transformer.h.0.mlp.c_proj.weight', 'transformer.h.0.mlp.c_proj.bias', 'transformer.h.1.ln_1.weight', 'transformer.h.1.ln_1.bias', 'transformer.h.1.attn.bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.1.attn.c_attn.weight', 'transformer.h.1.attn.c_attn.bias', 'transformer.h.1.attn.c_proj.weight', 'transformer.h.1.attn.c_proj.bias', 'transformer.h.1.ln_2.weight', 'transformer.h.1.ln_2.bias', 'transformer.h.1.mlp.c_fc.weight', 'transformer.h.1.mlp.c_fc.bias', 'transformer.h.1.mlp.c_proj.weight', 'transformer.h.1.mlp.c_pr

In [5]:
a

OrderedDict([('transformer.wte.weight',
              tensor([[-0.1101, -0.0393,  0.0331,  ..., -0.1364,  0.0151,  0.0453],
                      [ 0.0403, -0.0486,  0.0462,  ...,  0.0861,  0.0025,  0.0432],
                      [-0.1275,  0.0479,  0.1841,  ...,  0.0899, -0.1297, -0.0879],
                      ...,
                      [-0.0445, -0.0548,  0.0123,  ...,  0.1044,  0.0978, -0.0695],
                      [ 0.1860,  0.0167,  0.0461,  ..., -0.0963,  0.0785, -0.0225],
                      [ 0.0514, -0.0277,  0.0499,  ...,  0.0070,  0.1552,  0.1207]])),
             ('transformer.wpe.weight',
              tensor([[-1.8821e-02, -1.9742e-01,  4.0267e-03,  ..., -4.3044e-02,
                        2.8267e-02,  5.4490e-02],
                      [ 2.3959e-02, -5.3792e-02, -9.4879e-02,  ...,  3.4170e-02,
                        1.0172e-02, -1.5573e-04],
                      [ 4.2161e-03, -8.4764e-02,  5.4515e-02,  ...,  1.9745e-02,
                        1.9325e-02, -2.1424

In [2]:
b=torch.load("/home/haoooooooooooookkkkk/sophomore_autumn/ANN/HW3/HW3/codes/train/checkpoint_fresh3.bin")

In [7]:
b.keys()

odict_keys(['transformer.wte.weight', 'transformer.wpe.weight', 'transformer.h.0.ln_1.weight', 'transformer.h.0.ln_1.bias', 'transformer.h.0.attn.bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.0.attn.c_attn.weight', 'transformer.h.0.attn.c_attn.bias', 'transformer.h.0.attn.c_proj.weight', 'transformer.h.0.attn.c_proj.bias', 'transformer.h.0.ln_2.weight', 'transformer.h.0.ln_2.bias', 'transformer.h.0.mlp.c_fc.weight', 'transformer.h.0.mlp.c_fc.bias', 'transformer.h.0.mlp.c_proj.weight', 'transformer.h.0.mlp.c_proj.bias', 'transformer.h.1.ln_1.weight', 'transformer.h.1.ln_1.bias', 'transformer.h.1.attn.bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.1.attn.c_attn.weight', 'transformer.h.1.attn.c_attn.bias', 'transformer.h.1.attn.c_proj.weight', 'transformer.h.1.attn.c_proj.bias', 'transformer.h.1.ln_2.weight', 'transformer.h.1.ln_2.bias', 'transformer.h.1.mlp.c_fc.weight', 'transformer.h.1.mlp.c_fc.bias', 'transformer.h.1.mlp.c_proj.weight', 'transformer.h.1.mlp.c_pr

In [5]:
print(a.keys())
print(b.keys())
print(a['transformer.h.0.attn.bias'])
print(b['transformer.h.0.attn.bias'])

odict_keys(['transformer.wte.weight', 'transformer.wpe.weight', 'transformer.h.0.ln_1.weight', 'transformer.h.0.ln_1.bias', 'transformer.h.0.attn.bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.0.attn.c_attn.weight', 'transformer.h.0.attn.c_attn.bias', 'transformer.h.0.attn.c_proj.weight', 'transformer.h.0.attn.c_proj.bias', 'transformer.h.0.ln_2.weight', 'transformer.h.0.ln_2.bias', 'transformer.h.0.mlp.c_fc.weight', 'transformer.h.0.mlp.c_fc.bias', 'transformer.h.0.mlp.c_proj.weight', 'transformer.h.0.mlp.c_proj.bias', 'transformer.h.1.ln_1.weight', 'transformer.h.1.ln_1.bias', 'transformer.h.1.attn.bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.1.attn.c_attn.weight', 'transformer.h.1.attn.c_attn.bias', 'transformer.h.1.attn.c_proj.weight', 'transformer.h.1.attn.c_proj.bias', 'transformer.h.1.ln_2.weight', 'transformer.h.1.ln_2.bias', 'transformer.h.1.mlp.c_fc.weight', 'transformer.h.1.mlp.c_fc.bias', 'transformer.h.1.mlp.c_proj.weight', 'transformer.h.1.mlp.c_pr

In [10]:
a.values()

odict_values([tensor([[-0.1101, -0.0393,  0.0331,  ..., -0.1364,  0.0151,  0.0453],
        [ 0.0403, -0.0486,  0.0462,  ...,  0.0861,  0.0025,  0.0432],
        [-0.1275,  0.0479,  0.1841,  ...,  0.0899, -0.1297, -0.0879],
        ...,
        [-0.0445, -0.0548,  0.0123,  ...,  0.1044,  0.0978, -0.0695],
        [ 0.1860,  0.0167,  0.0461,  ..., -0.0963,  0.0785, -0.0225],
        [ 0.0514, -0.0277,  0.0499,  ...,  0.0070,  0.1552,  0.1207]]), tensor([[-1.8821e-02, -1.9742e-01,  4.0267e-03,  ..., -4.3044e-02,
          2.8267e-02,  5.4490e-02],
        [ 2.3959e-02, -5.3792e-02, -9.4879e-02,  ...,  3.4170e-02,
          1.0172e-02, -1.5573e-04],
        [ 4.2161e-03, -8.4764e-02,  5.4515e-02,  ...,  1.9745e-02,
          1.9325e-02, -2.1424e-02],
        ...,
        [-1.7987e-03,  1.6052e-03, -5.5103e-02,  ...,  1.3617e-02,
         -7.1805e-03,  3.7552e-03],
        [ 3.2105e-03,  1.5501e-03, -4.8944e-02,  ...,  2.0725e-02,
         -1.1838e-02, -5.5683e-04],
        [ 2.6610e-04,  

In [11]:
b.values()

odict_values([tensor([[ 0.0286, -0.0268,  0.0281,  ...,  0.0024, -0.0181,  0.0048],
        [-0.0121, -0.0840,  0.0059,  ...,  0.0512,  0.0084,  0.0005],
        [ 0.0395, -0.0021,  0.0190,  ...,  0.0051,  0.0010, -0.0117],
        ...,
        [-0.0137, -0.0051,  0.0102,  ...,  0.0120, -0.0043,  0.0076],
        [ 0.0311,  0.0026,  0.0326,  ..., -0.0223, -0.0240,  0.0292],
        [ 0.0013, -0.0188,  0.0085,  ...,  0.0109,  0.0049,  0.0027]],
       device='cuda:0'), tensor([[-9.0005e-03,  2.3478e-02, -1.2699e-02,  ...,  1.2429e-02,
          4.7170e-02, -1.8066e-02],
        [ 1.0012e-03,  1.3031e-02, -2.1879e-03,  ...,  2.4910e-02,
          6.0205e-03, -4.7104e-03],
        [-2.9096e-03,  1.8513e-03,  1.1121e-02,  ..., -4.4652e-04,
          1.9981e-02,  2.4010e-02],
        ...,
        [-2.1188e-02, -5.1486e-03, -8.1432e-03,  ..., -4.8717e-03,
          1.0231e-02, -2.1841e-03],
        [-3.1497e-05,  2.5961e-02,  2.2542e-02,  ..., -1.9683e-02,
          1.0429e-02, -1.2077e-02],

In [12]:
a=torch.arange(9,0,-1).reshape(3,3)
a

tensor([[9, 8, 7],
        [6, 5, 4],
        [3, 2, 1]])

In [13]:
up,indices=torch.sort(a,dim=-1)
up
indices

tensor([[2, 1, 0],
        [2, 1, 0],
        [2, 1, 0]])

In [14]:
up

tensor([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])

In [15]:
e=torch.empty()

TypeError: empty() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


In [16]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [17]:
a=torch.arange(0,9,1).reshape(3,3)
b=torch.arange(9,0,-1).reshape(3,3)
for i,j in zip(a,b):
    print(i,j)
    print("aaaaaaaaaaa")

tensor([0, 1, 2]) tensor([9, 8, 7])
aaaaaaaaaaa
tensor([3, 4, 5]) tensor([6, 5, 4])
aaaaaaaaaaa
tensor([6, 7, 8]) tensor([3, 2, 1])
aaaaaaaaaaa


In [18]:
a=torch.arange(0,9)
b=torch.cumsum(a,dim=-1)
b

tensor([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [3]:
a=torch.arange(0,9)
b=torch.cumsum(a,dim=-1)
b

tensor([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [4]:
a=torch.arange(0,6).reshape(2,3)
b=torch.multinomial(a.to(float),1)
b

tensor([[2],
        [2]])

In [5]:
b.shape

torch.Size([2, 1])

In [6]:
a=torch.tensor(5)
a

tensor(5)

In [11]:
a.var()

RuntimeError: std and var only support floating point and complex dtypes

In [8]:
vars(a)

{}

In [9]:
a.item

<function Tensor.item>

In [10]:
a.item()

5

In [16]:
a=torch.randn(5)
b,bi=torch.sort(a,descending=True)
c,ci=torch.sort(a,descending=False)
print(b)
print(c)

tensor([ 0.4796, -0.1954, -0.4019, -0.5837, -0.9382])
tensor([-0.9382, -0.5837, -0.4019, -0.1954,  0.4796])


In [17]:
c.cumsum(dim=-1)

tensor([-0.9382, -1.5219, -1.9238, -2.1192, -1.6396])

In [18]:
d=c<0
d

tensor([ True,  True,  True,  True, False])

In [21]:
not True

False

In [22]:
not d

RuntimeError: Boolean value of Tensor with more than one value is ambiguous

In [9]:
a=torch.zeros(5,1,dtype=int)
b=torch.randn(5,1)
c=torch.empty_like(b).scatter_(1,a,b)
print(a)
print(b)
print(c)

tensor([[0],
        [0],
        [0],
        [0],
        [0]])
tensor([[ 0.2909],
        [-0.0967],
        [ 1.2385],
        [-0.9814],
        [-0.4510]])
tensor([[ 0.2909],
        [-0.0967],
        [ 1.2385],
        [-0.9814],
        [-0.4510]])


In [14]:
import sys
sys.path.append('/home/haoooooooooooookkkkk/sophomore_autumn/ANN/HW3/HW3/codes')
from tokenizer import get_tokenizer

tokenizer=get_tokenizer('/home/haoooooooooooookkkkk/sophomore_autumn/ANN/HW3/HW3/codes/tokenizer')
with open('result.txt','w') as w:
    with open('temp.txt','r') as f:
        lines=f.readlines()
        for i in lines:
            w.write(str(tokenizer.tokenize(i))+'\n')


