In [1]:
3*32*32

3072

In [2]:
import torch

In [3]:
torch.tensor(5)

tensor(5)

In [4]:
a=torch.randn(2,3,4)

In [5]:
a

tensor([[[-2.7742,  0.4814,  0.2794,  0.1114],
         [-0.3730, -0.6879, -0.8544, -0.5531],
         [-0.4275, -1.8049,  0.1756,  0.8839]],

        [[ 2.2297,  0.3745, -0.4486,  1.4017],
         [ 0.2059,  0.7809,  0.1959, -0.3186],
         [-1.1464,  1.2297, -1.6611,  0.2245]]])

In [6]:
torch.mean(a,dim=(1,2))

tensor([-0.4619,  0.2557])

In [8]:
c=torch.var(a, dim=(1,2))

In [9]:
c

tensor([1.0326, 1.1747])

In [10]:
c[:,None]

tensor([[1.0326],
        [1.1747]])

In [11]:
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
b=torch.zeros(2,3,4,5)

In [14]:
b.shape

torch.Size([2, 3, 4, 5])

In [15]:
c=torch.reshape(b,(2,-1))

In [16]:
c.shape

torch.Size([2, 60])